// Generated by CoffeeScript 1.6.3
/*
    The Objectives are mearly a sub set of important infomation from the grid this is done to allow for caching and faster look up on the browser side because it is        faster to look up 5-10 objectives than it is to loop over 100+ grid points.
*/


(function() {
  var DialogController, GridController, GridPoint, Objective, app, currentController, randomWrong, shuffle, speaker;

  currentController = {};

  Objective = (function() {
    function Objective(name, description, failedMessage, pointid, image) {
      this.name = name;
      this.description = description;
      this.pointid = pointid;
      this.failedMessage = failedMessage;
      this.completed = false;
      this.image = image;
    }

    return Objective;

  })();

  GridPoint = (function() {
    function GridPoint(image, backImage, name, description, failedMessage, size, pointid) {
      this.id = pointid;
      this.image = image;
      this.backImage = backImage;
      this.size = size;
      this.name = name;
      this.description = description;
      this.failedMessage = failedMessage;
    }

    return GridPoint;

  })();

  randomWrong = function() {
    var i, indexes;
    indexes = [
      {
        row: 50,
        col: 0
      }, {
        row: 150,
        col: 0
      }, {
        row: 0,
        col: 50
      }, {
        row: 100,
        col: 50
      }, {
        row: 150,
        col: 50
      }
    ];
    i = Math.floor(Math.random() * 5);
    return indexes[i];
  };

  shuffle = function(array) {
    var currentIndex, randomIndex, temporaryValue;
    currentIndex = array.length;
    temporaryValue = {};
    randomIndex = 0;
    while (0 !== currentIndex) {
      randomIndex = Math.floor(Math.random() * currentIndex);
      currentIndex -= 1;
      temporaryValue = array[currentIndex];
      array[currentIndex] = array[randomIndex];
      array[randomIndex] = temporaryValue;
    }
    return array;
  };

  app = angular.module('ShaniquaApp', ['timer']);

  app.controller('GridController', GridController = (function() {
    GridController.$inject = ['$interval', '$scope'];

    GridController.prototype.CurrentObjective = 0;

    GridController.prototype.Objectives = [];

    GridController.prototype.Grids = [];

    GridController.prototype.StopTimer = [];

    GridController.prototype.ForegroundImageName = 'backgrounds.png';

    GridController.prototype.BackgroundImageName = 'items.png';

    GridController.prototype.StageName = 'Shaniquia in the mall';

    GridController.prototype.size = 16;

    GridController.prototype.spriteSheet = {
      boxSize: 50,
      squareLength: 4
    };

    GridController.prototype.length = 4;

    GridController.prototype.getObjectiveStyle = function(objective) {
      return {
        'width': '50px',
        'height': '50px',
        'background-image': 'url("images/items.png")',
        'background-repeat': 'no-repeat',
        'background-position': -objective.image.row + 'px ' + -objective.image.col + 'px'
      };
    };

    GridController.prototype.getBackgroundStyle = function(point) {
      return {
        'width': '50px',
        'height': '50px',
        'background-image': 'url("images/items.png")',
        'background-repeat': 'no-repeat',
        'background-position': -point.backImage.row + 'px ' + -point.backImage.col + 'px'
      };
    };

    GridController.prototype.getForegroundStyle = function(point) {
      return {
        'width': '50px',
        'height': '50px',
        'background-image': 'url("images/backgrounds.png") ',
        'background-repeat': 'no-repeat',
        'background-position': -point.image.row + 'px ' + -point.image.col + 'px'
      };
    };

    GridController.prototype.createForegrounds = function() {
      var col, foreground, i, length, row, _i;
      foreground = [];
      length = this.spriteSheet.squareLength * this.spriteSheet.squareLength;
      for (i = _i = 0; 0 <= length ? _i < length : _i > length; i = 0 <= length ? ++_i : --_i) {
        row = i % this.spriteSheet.squareLength;
        col = Math.floor(i / this.spriteSheet.squareLength);
        foreground[i] = {
          row: row * 50,
          col: col * 50
        };
      }
      return shuffle(foreground);
    };

    GridController.prototype.createObjectives = function() {
      var point, _i, _len, _ref;
      _ref = this.Grids;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        point = _ref[_i];
        this.Objectives.push(new Objective(point.name, point.description, point.failedMessage, point.id, point.backImage));
      }
      this.Objectives[0].timer = '0:00';
      this.Objectives[0].timeinSeconds = -1;
      return this.CurrentObjective = 0;
    };

    GridController.prototype.createGridPoints = function() {
      var foregrounds, i, nondummyItems, _i, _ref;
      foregrounds = this.createForegrounds();
      this.Grids.push(new GridPoint(foregrounds[0], {
        row: 0,
        col: 0
      }, 'Shaniqua', 'Shaniqua is lost help find her', 'Shaniqua', 20, 0));
      this.Grids.push(new GridPoint(foregrounds[1], {
        row: 50,
        col: 50
      }, "Shaniqua's purse", 'Shaniqua lost her pruse help her find it', "her purse!", 20, 1));
      this.Grids.push(new GridPoint(foregrounds[2], {
        row: 100,
        col: 0
      }, "Shaniqua's lipstick", 'Shaniqua is lost her lipstick help her find it', "her lipstick!", 20, 2));
      this.createObjectives();
      nondummyItems = this.Grids.length - 1;
      for (i = _i = nondummyItems, _ref = this.size; nondummyItems <= _ref ? _i < _ref : _i > _ref; i = nondummyItems <= _ref ? ++_i : --_i) {
        this.Grids.push(new GridPoint(foregrounds[i], randomWrong(), '', '', '', 20, i));
      }
      return shuffle(this.Grids);
    };

    GridController.prototype.checkGridPoint = function(point) {
      var found;
      found = false;
      if (point.id === this.Objectives[this.CurrentObjective].pointid) {
        found = true;
      }
      if (found) {
        this.Objectives[this.CurrentObjective].completed = true;
        this.rootScope.$parent.$broadcast('thank-you', this.Objectives[this.CurrentObjective].name);
        this.CurrentObjective++;
        if (this.CurrentObjective === this.Objectives.length) {
          return this.StopTimer();
        }
      } else {
        this.Objectives[this.CurrentObjective].timeinSeconds += 10;
        this.rootScope.$parent.$broadcast('failed-to-find', this.Objectives[this.CurrentObjective].failedMessage);
        return this.rootScope.$broadcast('timer-add-time', 10);
      }
    };

    function GridController(interval, $scope) {
      this.interval = interval;
      this.rootScope = $scope;
      currentController = this.Objectives;
      this.StopTimer = function() {
        return this.rootScope.$parent.$broadcast('timer-stop');
      };
      this.rootScope.$on('finished-conversation', function(event) {
        return event.currentScope.grid.createGridPoints();
      });
    }

    return GridController;

  })());

  /*
     Dialog functionallity.
  */


  speaker = (function() {
    function speaker(name, image, text) {
      this.name = name;
      this.image = image;
      this.text = text;
    }

    return speaker;

  })();

  app.controller('DialogController', DialogController = (function() {
    DialogController.prototype.CurrentDialog = [];

    DialogController.prototype.CurrentDialogIndex = 0;

    DialogController.prototype.Showing = false;

    DialogController.prototype.Finished = false;

    DialogController.prototype.isGenericMessage = false;

    DialogController.prototype.isRedMessage = false;

    DialogController.prototype.isGreenMessage = false;

    DialogController.prototype.Conversation = [];

    DialogController.$inject = ['$interval', '$scope'];

    DialogController.prototype.ThankYou = function(item) {
      this.Conversation = [];
      this.Conversation.push(new speaker('Alexis ', 'red', "You found " + item));
      this.isGenericMessage = true;
      this.Showing = true;
      this.isGreenMessage = true;
      return this.CurrentDialog.push(this.Conversation[0]);
    };

    DialogController.prototype.Failed = function(item) {
      this.Conversation = [];
      this.Conversation.push(new speaker('Alexis ', 'red', "That is not " + item));
      this.isGenericMessage = true;
      this.Showing = true;
      this.isRedMessage = true;
      return this.CurrentDialog.push(this.Conversation[0]);
    };

    DialogController.prototype.FinishConversating = function() {
      this.rootScope.$parent.$broadcast('timer-start');
      this.rootScope.$parent.$broadcast('finished-conversation');
      return this.Showing = false;
    };

    DialogController.prototype.CreateConversation = function() {
      this.Conversation.push(new speaker('Phone', 'red', "Ring Ring "));
      this.Conversation.push(new speaker('Alexis', 'red', "Hello"));
      this.Conversation.push(new speaker('Caller', 'red', "Is Shaniqua there?"));
      this.Conversation.push(new speaker('Alexis', 'red', "No I think she is at the mall"));
      this.CurrentDialog.push(this.Conversation[0]);
      return this.Showing = true;
    };

    DialogController.prototype.CreateFinishingConversation = function(time) {
      this.Conversation = [];
      this.Conversation.push(new speaker('Alexis ', 'red', "You Found her and her stuff in: " + time));
      this.Finished = true;
      this.Showing = true;
      return this.CurrentDialog.push(this.Conversation[0]);
    };

    DialogController.prototype.NextDialog = function() {
      this.CurrentDialogIndex++;
      this.CurrentDialog.pop();
      if (this.CurrentDialogIndex === this.Conversation.length && !this.Finished && !this.isGenericMessage) {
        this.FinishConversating();
      } else if (!this.Finished && !this.isGenericMessage) {
        this.CurrentDialog.push(this.Conversation[this.CurrentDialogIndex]);
      } else {
        this.Showing = false;
      }
      this.isRedMessage = false;
      return this.isGreenMessage = false;
    };

    function DialogController(interval, $scope) {
      this.interval = interval;
      this.rootScope = $scope;
      this.CreateConversation();
      this.rootScope.$on('thank-you', function(event, item) {
        return event.currentScope.dialog.ThankYou(item);
      });
      this.rootScope.$on('failed-to-find', function(event, item) {
        return event.currentScope.dialog.Failed(item);
      });
      this.rootScope.$on('found-everything', function(event, time) {
        return event.currentScope.dialog.CreateFinishingConversation(time);
      });
    }

    return DialogController;

  })());

}).call(this);
